"""Domain enumerations for the banking transfer system."""

from __future__ import annotations

import enum


class Role(str, enum.Enum):
    CUSTOMER = "CUSTOMER"
    ADMIN = "ADMIN"


class AuthenticationStatus(str, enum.Enum):
    AUTHENTICATED = "AUTHENTICATED"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    LOCKED = "LOCKED"


class AccountStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"


class TransferStatus(str, enum.Enum):
    INITIATED = "INITIATED"
    VALIDATED = "VALIDATED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REVERSED = "REVERSED"


class FailureReasonCode(str, enum.Enum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    DAILY_LIMIT_EXCEEDED = "DAILY_LIMIT_EXCEEDED"
    SAME_ACCOUNT_TRANSFER = "SAME_ACCOUNT_TRANSFER"
    CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"
    CREDIT_FAILED = "CREDIT_FAILED"
    AUDIT_UNAVAILABLE = "AUDIT_UNAVAILABLE"
    EXTERNAL_TRANSFER_NOT_SUPPORTED = "EXTERNAL_TRANSFER_NOT_SUPPORTED"
    VELOCITY_ALERT = "VELOCITY_ALERT"
    REVERSAL_WINDOW_EXPIRED = "REVERSAL_WINDOW_EXPIRED"
    ALREADY_REVERSED = "ALREADY_REVERSED"


class AuditEventType(str, enum.Enum):
    INITIATED = "INITIATED"
    VALIDATED = "VALIDATED"
    DEBITED = "DEBITED"
    CREDITED = "CREDITED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"
    REVERSAL_INITIATED = "REVERSAL_INITIATED"
    REVERSAL_COMPLETED = "REVERSAL_COMPLETED"
    VELOCITY_ALERT = "VELOCITY_ALERT"
    STEP_UP_REQUESTED = "STEP_UP_REQUESTED"
    STEP_UP_COMPLETED = "STEP_UP_COMPLETED"
    FRAUD_SIGNAL = "FRAUD_SIGNAL"


class FraudTriggerRule(str, enum.Enum):
    VELOCITY = "VELOCITY"
    AMOUNT_DEVIATION = "AMOUNT_DEVIATION"
    DESTINATION_NOVELTY = "DESTINATION_NOVELTY"
    DAILY_LIMIT_PROXIMITY = "DAILY_LIMIT_PROXIMITY"


class FraudAction(str, enum.Enum):
    ALLOW = "ALLOW"
    STEP_UP = "STEP_UP"
    BLOCK = "BLOCK"


# PATTERN: LeastPrivilege — define the exact set of operations per role
class OperationKind(str, enum.Enum):
    POST_TRANSFERS = "POST_TRANSFERS"
    GET_TRANSFER_BY_ID = "GET_TRANSFER_BY_ID"
    POST_REVERSE = "POST_REVERSE"
    GET_BALANCE = "GET_BALANCE"
    GET_TRANSACTIONS = "GET_TRANSACTIONS"
    GET_AUDIT_ENTRIES = "GET_AUDIT_ENTRIES"
    GET_AUDIT_VERIFY = "GET_AUDIT_VERIFY"
    POST_STEP_UP = "POST_STEP_UP"
